#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scrnsaverproto
Version  : 1.2.2
Release  : 4
URL      : http://xorg.freedesktop.org/releases/individual/proto/scrnsaverproto-1.2.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/scrnsaverproto-1.2.2.tar.bz2
Summary  : ScrnSaver extension headers
Group    : Development/Tools
License  : X11
Requires: scrnsaverproto-doc
BuildRequires : libxslt-bin
BuildRequires : xmlto

%description
MIT Screen Saver Extension
This extension defines a protocol to control screensaver features
and also to query screensaver info on specific windows.

%package dev
Summary: dev components for the scrnsaverproto package.
Group: Development

%description dev
dev components for the scrnsaverproto package.


%package doc
Summary: doc components for the scrnsaverproto package.
Group: Documentation

%description doc
doc components for the scrnsaverproto package.


%prep
%setup -q -n scrnsaverproto-1.2.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/saver.h
/usr/include/X11/extensions/saverproto.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/scrnsaverproto/*
